-- Complete Seed Data for IGO AGRI TECH Products Catalog

-- Clear existing data if necessary (optional, commented out by default)
-- DELETE FROM products;

-- 1. Agri Farming Products -> Seeds & Plants
INSERT INTO products (id, category, subcategory, name, slug, description, price, price_label, status, is_featured, cover_url, sort_order) VALUES
(gen_random_uuid(), 'Agri Farming Products', 'Seeds & Plants', 'Premium Vegetable Seeds', 'premium-vegetable-seeds', 'High-germination rate professional vegetable seeds optimized for commercial Indian farming.', 250, 'per packet', 'active', true, '/assets/products/product_vegetable_seeds_1773126052340.png', 10),
(gen_random_uuid(), 'Agri Farming Products', 'Seeds & Plants', 'Commercial Fruit Plants', 'commercial-fruit-plants', 'Healthy, disease-resistant fruit plant saplings ready for greenhouse or open-field plantation.', 150, 'per sapling', 'active', false, '/assets/products/product_fruit_plants_1773126072148.png', 11),
(gen_random_uuid(), 'Agri Farming Products', 'Seeds & Plants', 'Hybrid Flower Seeds', 'hybrid-flower-seeds', 'Premium commercial flower seeds for floriculture businesses yielding vibrant, long-lasting blooms.', 400, 'per 100g', 'active', false, '/assets/products/product_flower_seeds_1773126088626.png', 12),
(gen_random_uuid(), 'Agri Farming Products', 'Seeds & Plants', 'Medicinal Plant Seedlings', 'medicinal-plant-seedlings', 'Cultivate high-value medicinal crops with our verified, robust nursery seedlings.', 60, 'per seedling', 'active', true, '/assets/products/product_medicinal_plants_1773126105976.png', 13);

-- 2. Agri Farming Products -> Fertilizers
INSERT INTO products (id, category, subcategory, name, slug, description, price, price_label, status, is_featured, cover_url, sort_order) VALUES
(gen_random_uuid(), 'Agri Farming Products', 'Fertilizers', 'Bulk NPK Fertilizer', 'bulk-npk-fertilizer', 'Essential macronutrient blend for rapid root growth and crop yield maximization.', 1200, 'per 50kg bag', 'active', true, '/assets/products/product_npk_fertilizer_1773126123240.png', 20),
(gen_random_uuid(), 'Agri Farming Products', 'Fertilizers', 'Premium Organic Fertilizer', 'premium-organic-fertilizer', '100% natural, nutrient-rich compost that improves soil structure and water retention.', 450, 'per 25kg bag', 'active', false, '/assets/products/product_organic_fertilizer_1773126139785.png', 21),
(gen_random_uuid(), 'Agri Farming Products', 'Fertilizers', 'Liquid Fertilizer Complex', 'liquid-fertilizer-complex', 'Fast-acting liquid nutrients designed for modern drip irrigation and foliar application.', 800, 'per 5 Liters', 'active', false, '/assets/products/product_liquid_fertilizer_1773126157337.png', 22),
(gen_random_uuid(), 'Agri Farming Products', 'Fertilizers', 'Essential Micronutrients', 'essential-micronutrients', 'Targeted trace mineral powder to resolve soil deficiencies and ensure perfect crop health.', 650, 'per 1kg pouch', 'active', false, '/assets/products/product_micronutrients_1773126173707.png', 23);

-- 3. Agri Farming Products -> Bio Fertilizers
INSERT INTO products (id, category, subcategory, name, slug, description, price, price_label, status, is_featured, cover_url, sort_order) VALUES
(gen_random_uuid(), 'Agri Farming Products', 'Bio Fertilizers', 'Azospirillum Bio-Culture', 'azospirillum-bio-culture', 'Nitrogen-fixing bio-fertilizer that significantly reduces chemical dependency.', 350, 'per Liter', 'active', true, '/assets/products/product_azospirillum_1773126188809.png', 30),
(gen_random_uuid(), 'Agri Farming Products', 'Bio Fertilizers', 'PSB (Phosphate Solubilizing Bacteria)', 'psb-bacteria', 'Unlocks bound soil phosphorus to make it easily accessible to plant roots.', 350, 'per Liter', 'active', false, '/assets/products/product_psb_fertilizer_1773126205348.png', 31),
(gen_random_uuid(), 'Agri Farming Products', 'Bio Fertilizers', 'Mycorrhiza Root Booster', 'mycorrhiza-root-booster', 'Beneficial fungi powder that expands root networks for massive nutrient uptake.', 500, 'per 500g', 'active', true, '/assets/products/product_mycorrhiza_1773126231621.png', 32);

-- 4. Agri Farming Products -> Plant Growth Supplements
INSERT INTO products (id, category, subcategory, name, slug, description, price, price_label, status, is_featured, cover_url, sort_order) VALUES
(gen_random_uuid(), 'Agri Farming Products', 'Plant Growth Supplements', 'Humic Acid Extract', 'humic-acid-extract', 'Concentrated organic acid to chelate soil nutrients and enhance seed germination.', 700, 'per Liter', 'active', false, '/assets/products/product_humic_acid_1773126246789.png', 40),
(gen_random_uuid(), 'Agri Farming Products', 'Plant Growth Supplements', 'Fulvic Acid Liquid', 'fulvic-acid-liquid', 'Premium molecular supplement that immediately transports nutrients directly into plant cells.', 900, 'per Liter', 'active', false, '/assets/products/product_fulvic_acid_1773126265049.png', 41),
(gen_random_uuid(), 'Agri Farming Products', 'Plant Growth Supplements', 'Amino Acid Concentrate', 'amino-acid-concentrate', 'Reduces plant stress and massively accelerates photosynthesis and fruit development.', 850, 'per Liter', 'active', true, '/assets/products/product_amino_acid_1773126282168.png', 42);

-- 5. Agri Farming Products -> Crop Protection
INSERT INTO products (id, category, subcategory, name, slug, description, price, price_label, status, is_featured, cover_url, sort_order) VALUES
(gen_random_uuid(), 'Agri Farming Products', 'Crop Protection', 'Commercial Insecticide', 'commercial-insecticide', 'Fast-acting, broad-spectrum control over severe agricultural pest infestations.', 1100, 'per Liter', 'active', false, '/assets/products/product_insecticides_1773126298190.png', 50),
(gen_random_uuid(), 'Agri Farming Products', 'Crop Protection', 'Systemic Fungicide', 'systemic-fungicide', 'Preventative and curative fungal infection control for high-yield farming.', 1300, 'per Liter', 'active', false, '/assets/products/product_fungicides_1773126316657.png', 51),
(gen_random_uuid(), 'Agri Farming Products', 'Crop Protection', 'Agricultural Herbicide', 'agricultural-herbicide', 'Efficient weed management chemical ensuring zero competition for your crops.', 950, 'per Liter', 'active', false, '/assets/products/product_herbicides_1773126334052.png', 52),
(gen_random_uuid(), 'Agri Farming Products', 'Crop Protection', 'Organic Bio Pesticide', 'organic-bio-pesticide', 'Eco-friendly pest control derived from natural extracts, safe for organic certification.', 1500, 'per Liter', 'active', true, 'https://images.unsplash.com/photo-1627914848507-2aeab145ceb1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 53);

-- 6. Aquaculture Products (Using high-quality Unsplash fallbacks combined with contextual farming images)
INSERT INTO products (id, category, subcategory, name, slug, description, price, price_label, status, is_featured, cover_url, sort_order) VALUES
(gen_random_uuid(), 'Aquaculture Products', 'Fish Feed', 'High-Protein Fish Feed', 'high-protein-fish-feed', 'Floating pellets designed for rapid weight gain across commercial pond fish species.', 1800, 'per 25kg bag', 'active', true, 'https://images.unsplash.com/photo-1596765798083-2fdb30cfdfb8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 60),
(gen_random_uuid(), 'Aquaculture Products', 'Aquaculture Equipment', 'Paddle Wheel Aerator', 'paddle-wheel-aerator', 'Heavy-duty 2HP mechanical aerator to maintain critical dissolved oxygen levels in fish ponds.', 25000, 'per unit', 'active', true, 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 61),
(gen_random_uuid(), 'Aquaculture Products', 'Aquaculture Equipment', 'Biofloc Tank Tarpaulin', 'biofloc-tank-tarpaulin', 'Thick, UV-stabilized PVC tarpaulin pre-welded for circular Biofloc system construction.', 12000, 'per tank liner', 'active', false, 'https://images.unsplash.com/photo-1623912197177-80be4cc31238?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 62),
(gen_random_uuid(), 'Aquaculture Products', 'Aquaculture Equipment', 'Pond Liner Sheet (HDPE)', 'pond-liner-sheet-hdpe', 'Industrial-grade leak-proof HDPE sheets for large scale aquaculture pond lining.', 150, 'per Sq.M', 'active', false, 'https://images.unsplash.com/photo-1534433726569-809ff473fc5a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 63),
(gen_random_uuid(), 'Aquaculture Products', 'Aquaculture Equipment', 'Master Water Testing Kit', 'master-water-testing-kit', 'Precision chemical testing kit for Ammonia, pH, Nitrite, and Dissolved Oxygen.', 2400, 'per kit', 'active', false, 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 64),
(gen_random_uuid(), 'Aquaculture Products', 'Fish Medicines', 'Aquaculture Medicine Mix', 'aquaculture-medicine-mix', 'Broad-spectrum anti-bacterial and anti-fungal treatments for healthy fish stock.', 850, 'per 500g', 'active', false, 'https://images.unsplash.com/photo-1588636239452-97b76a08dcbc?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 65);

-- 7. Livestock Products
INSERT INTO products (id, category, subcategory, name, slug, description, price, price_label, status, is_featured, cover_url, sort_order) VALUES
(gen_random_uuid(), 'Livestock Products', 'Livestock Feed', 'Premium Goat Feed', 'premium-goat-feed', 'Nutritionally balanced commercial feed promoting faster growth in meat goat breeds.', 1400, 'per 50kg bag', 'active', true, 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 70),
(gen_random_uuid(), 'Livestock Products', 'Livestock Feed', 'High-Yield Dairy Cattle Feed', 'high-yield-dairy-cattle-feed', 'Enriched pellet mix proven to increase daily milk yield and cattle immunity.', 1600, 'per 50kg bag', 'active', true, 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 71),
(gen_random_uuid(), 'Livestock Products', 'Livestock Feed', 'Livestock Mineral Mixture', 'livestock-mineral-mixture', 'Vital chelated trace minerals preventing reproductive issues and strengthening bone density.', 900, 'per 5kg', 'active', false, 'https://images.unsplash.com/photo-1596765798083-2fdb30cfdfb8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 72),
(gen_random_uuid(), 'Livestock Products', 'Livestock Medicines', 'Livestock Veterinary Medicine', 'livestock-veterinary-medicine', 'Essential dewormers and immune boosters for maintaining herd health.', 500, 'per vial', 'active', false, 'https://images.unsplash.com/photo-1588636239452-97b76a08dcbc?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 73),
(gen_random_uuid(), 'Livestock Products', 'Livestock Equipment', 'Farm Livestock Equipment', 'farm-livestock-equipment', 'Durable automated drinkers, feeders, and tagging systems for professional farm management.', 3500, 'per set', 'active', false, 'https://images.unsplash.com/photo-1554589255-bfa3bbfc158a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 74);

-- 8. Farm Engineering Products
INSERT INTO products (id, category, subcategory, name, slug, description, price, price_label, status, is_featured, cover_url, sort_order) VALUES
(gen_random_uuid(), 'Farm Engineering Products', 'Greenhouse Materials', 'Polyhouse Plastic Sheets', 'polyhouse-plastic-sheets', '200-micron UV-stabilized anti-drip poly sheets for optimal greenhouse climate control.', 65, 'per Sq.M', 'active', true, 'https://images.unsplash.com/photo-1591857177580-c20ecbe60882?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 80),
(gen_random_uuid(), 'Farm Engineering Products', 'Greenhouse Materials', 'Agricultural Shade Nets', 'agricultural-shade-nets', '50% to 75% shading factor nets to protect delicate crops from harsh Indian summers.', 35, 'per Sq.M', 'active', false, 'https://images.unsplash.com/photo-1589923188900-85dae523342b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 81),
(gen_random_uuid(), 'Farm Engineering Products', 'Greenhouse Materials', 'Anti-Insect Nets', 'anti-insect-nets', '40-mesh dense netting blocking whiteflies and aphids out of protected cultivation zones.', 45, 'per Sq.M', 'active', false, 'https://images.unsplash.com/photo-1591857177580-c20ecbe60882?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 82),
(gen_random_uuid(), 'Farm Engineering Products', 'Structures & Plumbing', 'Galvanized Iron (GI) Pipes', 'gi-pipes', 'Rust-resistant structural GI steel pipes for building robust polyhouse and net house frames.', 200, 'per pipe', 'active', false, 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 83),
(gen_random_uuid(), 'Farm Engineering Products', 'Hydroponics', 'Hydroponic NFT Channels', 'hydroponic-nft-channels', 'Food-grade UPVC gullies perfectly engineered for nutrient film technique leafy green farming.', 450, 'per 3 meter', 'active', true, 'https://images.unsplash.com/photo-1558221849-0607ce7b90db?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 84),
(gen_random_uuid(), 'Farm Engineering Products', 'Hydroponics', 'Hydroponic Net Pots', 'hydroponic-net-pots', 'Heavy-duty 2-inch plastic mesh pots for supporting rockwool or clay pebble grow media.', 5, 'per pot', 'active', false, 'https://images.unsplash.com/photo-1558221849-0607ce7b90db?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 85),
(gen_random_uuid(), 'Farm Engineering Products', 'Hydroponics', 'Commercial Hydroponic Nutrients', 'commercial-hydroponic-nutrients', 'Two-part A+B perfectly balanced liquid nutrient mix for soil-less agriculture.', 1800, 'per 10 Liter set', 'active', true, 'https://images.unsplash.com/photo-1584478332152-ed8524cbce8a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 86),
(gen_random_uuid(), 'Farm Engineering Products', 'Hydroponics', 'LED Grow Lights', 'led-grow-lights', 'Full-spectrum 100W LED fixtures replacing the sun for indoor vertical farming systems.', 4500, 'per light', 'active', false, 'https://images.unsplash.com/photo-1558221849-0607ce7b90db?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 87),
(gen_random_uuid(), 'Farm Engineering Products', 'Irrigation Systems', 'Heavy Duty Water Pumps', 'heavy-duty-water-pumps', 'Reliable centrifugal and submersible agricultural water pumps for borewells and tanks.', 8500, 'per pump', 'active', true, 'https://images.unsplash.com/photo-1596541223130-5d56441b80bf?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 88),
(gen_random_uuid(), 'Farm Engineering Products', 'Irrigation Systems', 'Complete Drip Irrigation System', 'complete-drip-irrigation-system', 'Precision water delivery network including laterals, emitters, and mainlines.', 25000, 'per acre setup', 'active', true, 'https://images.unsplash.com/photo-1563514258000-618d3f101235?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 89),
(gen_random_uuid(), 'Farm Engineering Products', 'Irrigation Systems', 'Micro Sprinklers', 'micro-sprinklers', 'Even-coverage overhead sprinklers for nurseries, orchards, and open fields.', 45, 'per sprinkler', 'active', false, 'https://images.unsplash.com/photo-1563514258000-618d3f101235?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 90),
(gen_random_uuid(), 'Farm Engineering Products', 'Irrigation Systems', 'PVC Irrigation Pipes', 'pvc-irrigation-pipes', 'High-pressure 6kg/cm2 PVC piping for main headers and sub-mains in fields.', 450, 'per pipe', 'active', false, 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 91),
(gen_random_uuid(), 'Farm Engineering Products', 'Solar Technology', 'Industrial Solar Dryers', 'industrial-solar-dryers', 'Zero-electricity solar thermal cabinets to cleanly dehydrate spices, fruits, and vegetables.', 45000, 'per dryer unit', 'active', true, 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 92),
(gen_random_uuid(), 'Farm Engineering Products', 'Solar Technology', 'Solar Powered Water Pumps', 'solar-powered-water-pumps', 'Off-grid solar panel and AC pump controller setup, eliminating farm diesel costs entirely.', 125000, 'per complete setup', 'active', true, 'https://images.unsplash.com/photo-1509391366360-2e959784a276?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 93),
(gen_random_uuid(), 'Farm Engineering Products', 'Solar Technology', 'Solar Farm Fencing Systems', 'solar-farm-fencing-systems', 'Non-lethal continuous high-voltage solar zapper fences to protect crops from wild animals.', 35000, 'per acre setup', 'active', true, 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80', 94);
